version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.4
    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install .[test] --use-feature=2020-resolver
      - run:
         name: 'Pylinting'
         command: |
           . venv/bin/activate
           pylint tap_twilio -d C,W,unexpected-keyword-arg,duplicate-code,too-many-arguments,too-many-locals,too-many-nested-blocks,useless-object-inheritance,no-self-argument,raising-non-exception,no-member
      - run:
          name: 'Unit Tests'
          command: echo "No unit tests :("

workflows:
  version: 2
  commit:
    jobs:
      - build

version: 2
jobs:
  build:
    docker:
      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/circle-ci:tap-tester-v4
    steps:
      - checkout
      - run:
          name: 'Setup virtual env'
          command: |
            python3 -mvenv /usr/local/share/virtualenvs/tap-twilio
            source /usr/local/share/virtualenvs/tap-twilio/bin/activate
            pip install -U 'pip<19.2' setuptools
            pip install .[dev]
      - add_ssh_keys
      - run:
          name: 'Integration Tests'
          command: |
            aws s3 cp s3://com-stitchdata-dev-deployment-assets/environments/tap-tester/sandbox dev_env.sh
            source dev_env.sh
            source /usr/local/share/virtualenvs/tap-tester/bin/activate
            run-test --tap=tap-twilio \
                       --target=target-stitch \
                       --orchestrator=stitch-orchestrator \
                       --email=harrison+sandboxtest@stitchdata.com \
                       --password=$SANDBOX_PASSWORD \
                       --client-id=50 \
                       tests
workflows:
  version: 2
  commit:
    jobs:
      - build
  build_daily:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build